### ISSUE TITLE
ffmpeg crashes if chapter start and end times are the same

### ISSUE THREAD

**Issue by digitalec** [digitalec/sonus#1]
With ffmpeg loglevel not set to quiet: `-to value smaller than -ss; aborting.`

Full traceback:

```
Traceback (most recent call last):
  File "/home/digitalec/.local/bin/sonus", line 8, in <module>
    sys.exit(main.main())
  File "/home/digitalec/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/digitalec/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/digitalec/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/digitalec/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/digitalec/.local/lib/python3.9/site-packages/sonus/main.py", line 106, in main
    chapterizer.main(tmpdir.name, output_path)
  File "/home/digitalec/.local/lib/python3.9/site-packages/sonus/chapterizer.py", line 176, in main
    split_chapters(timings, tmpdir)
  File "/home/digitalec/.local/lib/python3.9/site-packages/sonus/chapterizer.py", line 105, in split_chapters
    ffmpeg.run(stream)
  File "/home/digitalec/.local/lib/python3.9/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by digitalec** [comment]
Fixed in 0.4.1
