### ISSUE TITLE
Me again, i think i must have had a stroke

### ISSUE THREAD

**Issue by cerinawithasea** [digitalec/sonus#14]
[https://app.warp.dev/block/embed/tJdk8kZcOV3y45u0ebtNHq](url)
`sonus /Users/cerinawithasea/Downloads/MagnificentDelusionsPakistantheUnitedStatesand-102.odm
Output will be saved to: /Users/cerinawithasea/Music
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/sonus", line 8, in <module>
    sys.exit(main.main())
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sonus/main.py", line 118, in main
    get_book(arg, tmpdir.name)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sonus/main.py", line 126, in get_book
    downloader.download_audiobook(odm)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sonus/downloader.py", line 68, in download_audiobook
    self._verify_odm_file(odm_filename)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sonus/downloader.py", line 193, in _verify_odm_file
    with open(odm_filename, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/cerinawithasea/Downloads/MagnificentDelusionsPakistantheUnitedStatesand-102.odm'`
tried again
[https://app.warp.dev/block/pG1ABZKPqhFuxkin7XxxHN](url)
so i moved it to windows downloaded the parts (side note overdrive download would not work [https://app.warp.dev/block/PGdbKvO5qGCc3VEqE2OY1F](url)
and 
`sonus /Users/cerinawithasea/Downloads/Magnificent\ Delusions
Output will be saved to: /Users/cerinawithasea/Music
Found 0 files, containing 0 chapters..`
did i do that?

wanted to add , i used it an hour ago. i never even shut warp and it worked beautifully
`sonus /Users/cerinawithasea/Downloads/EarthlyBodies_9780593909157_10333526.odm
Output will be saved to: /Users/cerinawithasea/Music
Got title "Earthly Bodies" and author Vanessa Chakour from ODM file EarthlyBodies_9780593909157_10333526.odm
Downloading Earthly Bodies-part01.mp3
Downloading Earthly Bodies-part02.mp3
Downloading Earthly Bodies-part03.mp3
Downloading Earthly Bodies-part04.mp3
Downloading Earthly Bodies-part05.mp3
Downloading Earthly Bodies-part06.mp3
Downloading Earthly Bodies-part07.mp3
Downloading Earthly Bodies-part08.mp3
Downloading part 8 of 8... 100%
Found 8 files, containing 57 chapters...
Extracting chapter Earthly Bodies- Embracing Animal Nature from Earthly Bodies-part01.mp3
Extracting chapter Dedication from Earthly Bodies-part01.mp3
Extracting chapter Epigraph from Earthly Bodies-part01.mp3
Extracting chapter Author’s Note from Earthly Bodies-part01.mp3
Extracting chapter Preface- Freedom from Earthly Bodies-part01.mp3
Extracting chapter Part One- Enclosures from Earthly Bodies-part01.mp3
Extracting chapter Gray Wolves from Earthly Bodies-part01.mp3
Extracting chapter Chapter 1- Predators and Prey from Earthly Bodies-part01.mp3
Extracting chapter Bats from Earthly Bodies-part01.mp3
Extracting chapter Chapter 2- Seeing in the Dark from Earthly Bodies-part01.mp3
Extracting chapter Howler Monkeys from Earthly Bodies-part01.mp3
Extracting chapter Chapter 3- Fitting In from Earthly Bodies-part02.mp3
Extracting chapter Spotted Hyenas from Earthly Bodies-part02.mp3
Extracting chapter Chapter 4- Ravenous from Earthly Bodies-part02.mp3
Extracting chapter Cheetahs from Earthly Bodies-part02.mp3
Extracting chapter Chapter 5- Wanting to Be Wanted from Earthly Bodies-part02.mp3
Extracting chapter Part Two- Rehabilitation from Earthly Bodies-part02.mp3
Extracting chapter Vultures from Earthly Bodies-part02.mp3
Extracting chapter Chapter 6- Quarantine from Earthly Bodies-part03.mp3
Extracting chapter Coyotes from Earthly Bodies-part03.mp3
Extracting chapter Chapter 7- Between Two Worlds from Earthly Bodies-part03.mp3
Extracting chapter White-Tailed Deer from Earthly Bodies-part03.mp3
Extracting chapter Chapter 8- Fight, Flight, Freeze, Fawn from Earthly Bodies-part03.mp3
Extracting chapter Octopuses from Earthly Bodies-part04.mp3
Extracting chapter Chapter 9- Too Sensitive from Earthly Bodies-part04.mp3
Extracting chapter Seagulls from Earthly Bodies-part04.mp3
Extracting chapter Chapter 10- Lost at Sea from Earthly Bodies-part04.mp3
Extracting chapter Spiders from Earthly Bodies-part04.mp3
Extracting chapter Chapter 11- Weaving My Web from Earthly Bodies-part04.mp3
Extracting chapter Part Three- Soft Release from Earthly Bodies-part04.mp3
Extracting chapter Yellowstone Wolves from Earthly Bodies-part04.mp3
Extracting chapter Chapter 12- Out of Bounds from Earthly Bodies-part05.mp3
Extracting chapter Rusty-Patched Bumblebees from Earthly Bodies-part05.mp3
Extracting chapter Chapter 13- Searching for Nectar from Earthly Bodies-part05.mp3
Extracting chapter Wood Thrush from Earthly Bodies-part05.mp3
Extracting chapter Chapter 14- Semantics from Earthly Bodies-part05.mp3
Extracting chapter Seahorses from Earthly Bodies-part06.mp3
Extracting chapter Chapter 15- Remember Me from Earthly Bodies-part06.mp3
Extracting chapter Sea Lions from Earthly Bodies-part06.mp3
Extracting chapter Chapter 16- Play and Pleasure from Earthly Bodies-part06.mp3
Extracting chapter Red-Tailed Hawks from Earthly Bodies-part06.mp3
Extracting chapter Chapter 17- Local Cosmology from Earthly Bodies-part06.mp3
Extracting chapter Part Four- Homing from Earthly Bodies-part06.mp3
Extracting chapter Pigeons from Earthly Bodies-part06.mp3
Extracting chapter Chapter 18- Finding Home from Earthly Bodies-part07.mp3
Extracting chapter Monarch Butterflies from Earthly Bodies-part07.mp3
Extracting chapter Chapter 19- Genetic Memory from Earthly Bodies-part07.mp3
Extracting chapter Black Bears from Earthly Bodies-part07.mp3
Extracting chapter Chapter 20- Home Range from Earthly Bodies-part07.mp3
Extracting chapter Red Fox from Earthly Bodies-part07.mp3
Extracting chapter Chapter 21- Domestication Syndrome from Earthly Bodies-part08.mp3
Extracting chapter Beavers from Earthly Bodies-part08.mp3
Extracting chapter Chapter 22- Engineering from Earthly Bodies-part08.mp3
Extracting chapter Humans from Earthly Bodies-part08.mp3
Extracting chapter Chapter 23- Animal Nature from Earthly Bodies-part08.mp3
Extracting chapter For more information... from Earthly Bodies-part08.mp3
Extracting chapter Credits from Earthly Bodies-part08.mp3
Processing audiobook "Earthly Bodies - Embracing Animal Nature" by Vanessa Chakour
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/1 Earthly Bodies- Embracing Animal Nature.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/2 Dedication.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/3 Epigraph.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/4 Author’s Note.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/5 Preface- Freedom.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/6 Part One- Enclosures.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/7 Gray Wolves.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/8 Chapter 1- Predators and Prey.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/9 Bats.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/10 Chapter 2- Seeing in the Dark.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/11 Howler Monkeys.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/12 Chapter 3- Fitting In.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/13 Spotted Hyenas.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/14 Chapter 4- Ravenous.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/15 Cheetahs.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/16 Chapter 5- Wanting to Be Wanted.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/17 Part Two- Rehabilitation.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/18 Vultures.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/19 Chapter 6- Quarantine.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/20 Coyotes.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/21 Chapter 7- Between Two Worlds.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/22 White-Tailed Deer.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/23 Chapter 8- Fight, Flight, Freeze, Fawn.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/24 Octopuses.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/25 Chapter 9- Too Sensitive.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/26 Seagulls.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/27 Chapter 10- Lost at Sea.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/28 Spiders.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/29 Chapter 11- Weaving My Web.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/30 Part Three- Soft Release.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/31 Yellowstone Wolves.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/32 Chapter 12- Out of Bounds.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/33 Rusty-Patched Bumblebees.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/34 Chapter 13- Searching for Nectar.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/35 Wood Thrush.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/36 Chapter 14- Semantics.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/37 Seahorses.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/38 Chapter 15- Remember Me.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/39 Sea Lions.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/40 Chapter 16- Play and Pleasure.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/41 Red-Tailed Hawks.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/42 Chapter 17- Local Cosmology.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/43 Part Four- Homing.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/44 Pigeons.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/45 Chapter 18- Finding Home.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/46 Monarch Butterflies.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/47 Chapter 19- Genetic Memory.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/48 Black Bears.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/49 Chapter 20- Home Range.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/50 Red Fox.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/51 Chapter 21- Domestication Syndrome.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/52 Beavers.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/53 Chapter 22- Engineering.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/54 Humans.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/55 Chapter 23- Animal Nature.mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/56 For more information....mp3
Saving chapter to /Users/cerinawithasea/Music/Vanessa Chakour/Earthly Bodies - Embracing Animal Nature/57 Credits.mp3`

**Comment by cerinawithasea** [comment]
I dont know why my links create a search, maybe i am having a stroke

**Comment by cerinawithasea** [comment]
it seems to be working again (at least it has once)
sorry i am known for overreacting a teensy bit..that was weird tho
