### ISSUE TITLE
Error while downloading books that can "/" in their title

### ISSUE THREAD

**Issue by flintstones-fred** [digitalec/sonus#5]
Pretty much what it says in title. Here is the error log I get:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/sonus", line 8, in <module>
    sys.exit(main.main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sonus/main.py", line 118, in main
    get_book(arg, tmpdir.name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sonus/main.py", line 126, in get_book
    downloader.download_audiobook(odm)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sonus/downloader.py", line 86, in download_audiobook
    self._download_cover_image(self.cover_url, cover_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sonus/downloader.py", line 106, in _download_cover_image
    with open(cover_path, 'wb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/2p/64gpzcvd05g09q3wg80jxprm0000gn/T/tmp88bx21g8/Stephen King/11/22/63/11/22/63.jpg'
```

**Comment by digitalec** [comment]
Fixed in 0.6.1

**Comment by flintstones-fred** [comment]
It appears that I am getting a different error after upgrading to 0.6.1

`Traceback (most recent call last):
  File "/home/pranav/anaconda3/bin/sonus", line 8, in <module>
    sys.exit(main.main())
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/sonus/main.py", line 118, in main
    get_book(arg, tmpdir.name)
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/sonus/main.py", line 126, in get_book
    downloader.download_audiobook(odm)
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/sonus/downloader.py", line 69, in download_audiobook
    self._extract_author_title_urls_parts(odm_filename)
  File "/home/pranav/anaconda3/lib/python3.9/site-packages/sonus/downloader.py", line 140, in _extract_author_title_urls_parts
    title = clean_title(title)
NameError: name 'clean_title' is not defined
`

**Comment by digitalec** [comment]
Whoops! Forgot to update the method call after I moved it out of `_extract_author_title_urls_parts()`. Please try again, 0.6.2 pushed.

**Comment by flintstones-fred** [comment]
Sorry, it took me a while to test this out. As of 0.6.2, the code works without error. One thing I did notice is that it saved the book in a directory format where every single hyphen was treated as a new folder. So, I had something like Stephen King -> 11 -> 22 -> 63 -> all files. Not a big deal, but I am also not sure if it is an easy fix for you. 

I am also struggling with another book. But unlike in this case, I can't pinpoint what about that book is causing issues. Should I just open a new issue with error code I see?

**Comment by digitalec** [comment]
Sorry for the delay! I'm not sure why each hyphen was treated as a new directory. Even Windows allows hyphens. I tried looking for this book but everything is waitlisted at the moment.

Yes, please open a separate issue for the other book so we can keep them separate.

What OS are you using so I can try and replicate it (assuming I can get my hands on a copy)?

**Comment by digitalec** [comment]
I was able to get this book and test it. I was originally replacing special characters in the chapter name but not in the audiobook title which was the issue here. I have now included all aspects of the file path (author, title, chapter name) which produces the intended output:

![image](https://user-images.githubusercontent.com/31838395/222335746-5e819e0a-dc36-491f-9db5-b5ef86e03fb5.png)
