### ISSUE TITLE
Error i have only seen 2 times

### ISSUE THREAD

**Issue by cerinawithasea** [digitalec/sonus#8]
Both times i have seen this there has been more then one - in the folder title. probably has nothing to do with this but its all i noticed
2 times is not alot for me, i must use sonus 2o times a day
oh and also both these files errored out in the overdrive chapterizer in inaudible
i can add that but i gotta swap laptops
This is a macbook pro the other laptop is windows. It also got the same errors using sonus on windows (added below)

cerinawithasea@Cerinas-MacBook-Pro 1chapters %  sonus /Volumes/Books/2merge --ou
tput /Volumes/Books/2Combine
Output will be saved to: /Volumes/Books/2Combine
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/sonus", line 8, in <module>
    sys.exit(main.main())
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/main.py", line 99, in main
    chapterizer.main(arg, output_path, generic, offset, ffmpeg_debug)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/chapterizer.py", line 219, in main
    all_markers = scan_overdrive_metadata(file_list)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/chapterizer.py", line 22, in scan_overdrive_metadata
    audio_data = xmltodict.parse(xmlstring)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 30

sme book on windows
Microsoft Windows [Version 10.0.19045.4291]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Cerina>
C:\Users\Cerina>sonus C:\Users\Cerina\Documents\2combine\1working --output C:\2comb
Output will be saved to: C:\2comb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Scripts\sonus.exe\__main__.py", line 7, in <module>
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sonus\main.py", line 99, in main
    chapterizer.main(arg, output_path, generic, offset, ffmpeg_debug)
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sonus\chapterizer.py", line 219, in main
    all_markers = scan_overdrive_metadata(file_list)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sonus\chapterizer.py", line 22, in scan_overdrive_metadata
    audio_data = xmltodict.parse(xmlstring)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 30

C:\Users\Cerina>
C:\Users\Cerina>

**Comment by cerinawithasea** [comment]
error in inaudable
idk if this is helpful, just in case
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: An error occurred while parsing EntityName. Line 1, position 31.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseEntityName()
   at System.Xml.XmlTextReaderImpl.ParseEntityReference()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at AudibleConvertor.Overdrive.OverdriveXML2Chapters(String overdriveMetadata)
   at AudibleConvertor.Overdrive.ParseChapters()
   at AudibleConvertor.FormOverdrive.btnSelectFiles_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9232.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
inAudible
    Assembly Version: 1.0.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/inAudible/inAudible.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AudioSoundEditor
    Assembly Version: 1.0.0.0
    Win32 Version: 5.0.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/inAudible/AudioSoundEditor.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
RichTextBoxLinks
    Assembly Version: 1.0.1829.14763
    Win32 Version: 1.0.1829.14763
    CodeBase: file:///C:/Program%20Files%20(x86)/inAudible/RichTextBoxLinks.DLL
----------------------------------------
ProgressODoom
    Assembly Version: 1.0.5792.17418
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/inAudible/ProgressODoom.DLL
----------------------------------------
taglib-sharp
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/inAudible/taglib-sharp.DLL
----------------------------------------
INIFileParser
    Assembly Version: 1.7.1.0
    Win32 Version: 1.7.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/inAudible/INIFileParser.DLL
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
CustomScrollBar
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/inAudible/CustomScrollBar.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by cerinawithasea** [comment]
Oh i can produce the files if you need

**Comment by digitalec** [comment]
Looks like it might be an issue with the odm file maybe. Can you share the book titles or files so I can test from my end?

This error `not well-formed (invalid token): line 1, column 30` is telling you the 31st char (columns start at 0) is not valid.

**Comment by cerinawithasea** [comment]
sure where should i upload?

**Comment by cerinawithasea** [comment]
I just remembered i earned a prem acc here , i think it should be add free now.....
https://send.cm/d/15l29
i think i still have the other book out still would you like that one? i can redownload it 
I use a bash script to dl by the way

**Comment by cerinawithasea** [comment]
> Looks like it might be an issue with the odm file maybe. Can you share the book titles or files so I can test from my end?
> 

> > This error `not well-formed (invalid token): line 1, column 30` is telling you the 31st char (columns start at 0) is not valid

.

This makes very little sense to me, i can kinda use it and recognize patterns, but i am definitely like a tourist that fakes it till i make it

**Comment by cerinawithasea** [comment]
hey hi me again
i tried to download and chapter with sonus doing it all (because now i know i can) pretty much the same
was hoping it would be so simple
cerinawithasea@Cerinas-MacBook-Pro 1chapters % sonus /Volumes/Books/Internet\ Downloads/BloodSteel_9781666650877_10140825\ \(1\).odm --output /Volumes/Books/2Combine
Output will be saved to: /Volumes/Books/2Combine
Got title "Blood & Steel" and author Helen Scheuerer from ODM file BloodSteel_9781666650877_10140825 (1).odm
Downloading Blood & Steel-part01.mp3
Downloading Blood & Steel-part02.mp3
Downloading Blood & Steel-part03.mp3
Downloading Blood & Steel-part04.mp3
Downloading Blood & Steel-part05.mp3
Downloading Blood & Steel-part06.mp3
Downloading Blood & Steel-part07.mp3
Downloading Blood & Steel-part08.mp3
Downloading Blood & Steel-part09.mp3
Downloading Blood & Steel-part10.mp3
Downloading Blood & Steel-part11.mp3
Downloading Blood & Steel-part12.mp3
Downloading Blood & Steel-part13.mp3
Downloading part 13 of 13... 100%
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/sonus", line 8, in <module>
    sys.exit(main.main())
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/main.py", line 119, in main
    chapterizer.main(tmpdir.name, output_path, generic, offset, ffmpeg_debug)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/chapterizer.py", line 219, in main
    all_markers = scan_overdrive_metadata(file_list)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/chapterizer.py", line 22, in scan_overdrive_metadata
    audio_data = xmltodict.parse(xmlstring)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 30

**Comment by digitalec** [comment]
This is all set. See #6  - an ampersand was causing the error here.
